/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.101.3
*/

import { Contract as __Contract, Interface } from "fuels";
import type {
  Provider,
  Account,
  StorageSlot,
  Address,
  BigNumberish,
  BN,
  FunctionFragment,
  InvokeFunction,
} from 'fuels';

import type { Enum } from "./common";

export type IdentityInput = Enum<{ Address: AddressInput, ContractId: ContractIdInput }>;
export type IdentityOutput = Enum<{ Address: AddressOutput, ContractId: ContractIdOutput }>;

export type AddressInput = { bits: string };
export type AddressOutput = AddressInput;
export type AssetIdInput = { bits: string };
export type AssetIdOutput = AssetIdInput;
export type CallInfoInput = { caller_is_external: boolean, caller: IdentityInput, asset_id: AssetIdInput, amount: BigNumberish, called_contract_id: ContractIdInput, base_asset_id: AssetIdInput, contract_default_asset_id: AssetIdInput };
export type CallInfoOutput = { caller_is_external: boolean, caller: IdentityOutput, asset_id: AssetIdOutput, amount: BN, called_contract_id: ContractIdOutput, base_asset_id: AssetIdOutput, contract_default_asset_id: AssetIdOutput };
export type ContractIdInput = { bits: string };
export type ContractIdOutput = ContractIdInput;

const abi = {
  "programType": "contract",
  "specVersion": "1",
  "encodingVersion": "1",
  "concreteTypes": [
    {
      "type": "struct CallInfo",
      "concreteTypeId": "21523d9dc71daa9438de9db70617ffac7b6667f60c6cfbea022ac4f8df0fff64",
      "metadataTypeId": 3
    }
  ],
  "metadataTypes": [
    {
      "type": "b256",
      "metadataTypeId": 0
    },
    {
      "type": "bool",
      "metadataTypeId": 1
    },
    {
      "type": "enum std::identity::Identity",
      "metadataTypeId": 2,
      "components": [
        {
          "name": "Address",
          "typeId": 4
        },
        {
          "name": "ContractId",
          "typeId": 6
        }
      ]
    },
    {
      "type": "struct CallInfo",
      "metadataTypeId": 3,
      "components": [
        {
          "name": "caller_is_external",
          "typeId": 1
        },
        {
          "name": "caller",
          "typeId": 2
        },
        {
          "name": "asset_id",
          "typeId": 5
        },
        {
          "name": "amount",
          "typeId": 7
        },
        {
          "name": "called_contract_id",
          "typeId": 6
        },
        {
          "name": "base_asset_id",
          "typeId": 5
        },
        {
          "name": "contract_default_asset_id",
          "typeId": 5
        }
      ]
    },
    {
      "type": "struct std::address::Address",
      "metadataTypeId": 4,
      "components": [
        {
          "name": "bits",
          "typeId": 0
        }
      ]
    },
    {
      "type": "struct std::asset_id::AssetId",
      "metadataTypeId": 5,
      "components": [
        {
          "name": "bits",
          "typeId": 0
        }
      ]
    },
    {
      "type": "struct std::contract_id::ContractId",
      "metadataTypeId": 6,
      "components": [
        {
          "name": "bits",
          "typeId": 0
        }
      ]
    },
    {
      "type": "u64",
      "metadataTypeId": 7
    }
  ],
  "functions": [
    {
      "name": "non_payable_call",
      "inputs": [],
      "output": "21523d9dc71daa9438de9db70617ffac7b6667f60c6cfbea022ac4f8df0fff64",
      "attributes": null
    },
    {
      "name": "payable_call",
      "inputs": [],
      "output": "21523d9dc71daa9438de9db70617ffac7b6667f60c6cfbea022ac4f8df0fff64",
      "attributes": [
        {
          "name": "payable",
          "arguments": []
        }
      ]
    }
  ],
  "loggedTypes": [],
  "messagesTypes": [],
  "configurables": [],
  "errorCodes": {}
};

const storageSlots: StorageSlot[] = [];

export class CallingContractsInterface extends Interface {
  constructor() {
    super(abi);
  }

  declare functions: {
    non_payable_call: FunctionFragment;
    payable_call: FunctionFragment;
  };
}

export class CallingContracts extends __Contract {
  static readonly abi = abi;
  static readonly storageSlots = storageSlots;

  declare interface: CallingContractsInterface;
  declare functions: {
    non_payable_call: InvokeFunction<[], CallInfoOutput>;
    payable_call: InvokeFunction<[], CallInfoOutput>;
  };

  constructor(
    id: string | Address,
    accountOrProvider: Account | Provider,
  ) {
    super(id, abi, accountOrProvider);
  }
}
