/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.101.3
*/

import { ContractFactory as __ContractFactory, decompressBytecode } from "fuels";
import type { Provider, Account, DeployContractOptions } from "fuels";

import { MintAndTransfer } from "./MintAndTransfer";

const bytecode = decompressBytecode("H4sIAAAAAAAAA41WzW8bRRR/ttMkFS0ZMKrSaUtW0FYpysFS09JDELtdL+vgGI9xIiLBsmORVIAgRI4bRUJIPiJOLQjIgYNPkBuOHUuV4OA/gIMPHDj6EqFAohqpkRL1EH6zu05cO4GuZL3x+5r3fu9jl7diVCDqI+8ZXPPp6ZhzUA+xgwMlI74t6D6dajlm6ywzqJ6PhwWLz+l8i5G2d51mHzfD4nGzr0ChOfdhYw3yxAny9yD/Wdi1lWNkDk82SKTLTZlig+6OdknuxJhI15oyXWZOihFLjRddK0bCrpSkDZ5dnoZ+w91hHPoXBHjSgk2ylpCTDLRcd3doOK/T86Dnhbm+Jg0N/I1hT25vjEqLGN/SiG/2xJNYfhR6GTk/q3JGzAmRrGjwE4e/86CWMCsi8Hcr8Jf4D3/jy48oDNvPb+pEwqwBH+rWuRi1G7QcpyioDhq6CfyFvf7A3WavimT1gbLhm1q33QJy1WWyoQlgJ1OahphWEdMo6jcEe3K3Cbzq6gn278NeO87esVtDzGL13ljpH26qeq3fgv4o8Bhz0uUxYZal1KUmsrWizODObK0uM8yj4p31D+UMeIbQpME0YKHfzkwrLOoiu97y9M2qwnTUMcvfRA2iZZ04zh/jrOMcRj2e8fGrCmHQIOpSAuYasF/xqFndU73FN3uw/QA5lrwczSqThg6bakxamjZhjas+/6nD56zny63NdvkY4+82iE8TnTNmikE8Z1Q8fEv01DsKfKBzHVTFfg35hqPm74p3CedIcH4O577gfAo92kStJpBPXfUS4upHn91D/d/Ox6kPvZ5ty1Cjhuq7QKcIHQGdCHQyvgw69kYTObZ1FqHzFnTC0En7Ms9PK/CD+ysx6LyBn+3zlY8aBT5UfKOQXUGMV30+5Gb1S9SToU6loE4h6EbwP6/iiRp9bd5EL070V4DT1Q58LnTgo2KSuG8Kc81UPLBhOfiLWrgrTv0qn+COcM4QZyAPq7nJGZnT2BU64k04Bp1Cj076PtSs1rSjnCoMOrdxh+nzFSa12BG25RbkL+asrMJtxJd5ea+o+UeeP3bkjZ4oLwa9G2YzQr9L9JUwN2alsah67g9/Brv3A/2Ce4rSRH/alYbfy5WW6tPXrOnGFeSDXmPBLjpmt9JZjt2BHVVGbNoNSyNl8y1R6LtBf4c7Zon4LtEq/n8P/pt7nnyoLedmkxy7RI7FyEmWKD9Fg2zyct1V+2wXM7V/aDsU2I60be9jJLnyb98jnmySfFhi/O9yd4yv8DRizGJPZxj2pN4tfymael2PpmLEBfCbomHs95hMqZ0a69a9HPjST/B10cMji72WUfY98oFrmfEv+K5OX6vY97V2biNBbpGO3JjCRuWEd05IYQEb1oFH5H9sPPxOsOnEUHZi6KRLhHegBgx0vAM1J0WUx/iw1A1yDbwHTeSmfuiVwL88Jo+Bzvrm8E6JTjJ9OYG5SWBurBeKmKEw+P2HcxMP9XXVe6C3V1SczScwRZ/zc5NDOvrmAP7VLIRyqQhyRz33WXfvHGLFTeQLX/LPEvIA70jXw8hGTJ9+tFBw5+bv5O5+UnBzS0vz6sPkKZ5CPrewdGc+/6StW/gskP/mPRQ+8B4KBd9BKz4d+NWn/T/4NML+BXaWh1wwCQAA");

export class MintAndTransferFactory extends __ContractFactory<MintAndTransfer> {

  static readonly bytecode = bytecode;

  constructor(accountOrProvider: Account | Provider) {
    super(
      bytecode,
      MintAndTransfer.abi,
      accountOrProvider,
      MintAndTransfer.storageSlots
    );
  }

  static deploy (
    wallet: Account,
    options: DeployContractOptions = {}
  ) {
    const factory = new MintAndTransferFactory(wallet);
    return factory.deploy(options);
  }
}
